// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function isValidHttpUrl(url?: string): boolean {
  if (!url || typeof url !== "string") return false;
  try {
    const parsed = new URL(url);
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!isValidHttpUrl(SUPABASE_URL) || !SUPABASE_SERVICE_ROLE_KEY) {
    console.warn("[Supabase Admin] Missing or invalid SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY.");
    return null;
  }

  try {
    return createClient<Database>(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  } catch (err) {
    console.warn("[Supabase Admin] Failed to create client:", err);
    return null;
  }
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

export function getSupabaseAdmin() {
  if (_supabaseAdmin === undefined) {
    _supabaseAdmin = createSupabaseAdminClient();
  }
  return _supabaseAdmin;
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { getSupabaseAdmin } = await import("@/integrations/supabase/client.server");
export const supabaseAdmin = new Proxy(
  {} as unknown as NonNullable<ReturnType<typeof createSupabaseAdminClient>>,
  {
    get(_, prop, receiver) {
      if (_supabaseAdmin === undefined) _supabaseAdmin = createSupabaseAdminClient();
      if (!_supabaseAdmin) return undefined;
      return Reflect.get(_supabaseAdmin, prop, receiver);
    },
  },
);
